### ISSUE TITLE
Creating an app without one of the provided technologies

### ISSUE THREAD

**Issue by mgrsskls** [experimental-platform/platform-configure-script#10]
It would be cool if one could create an "app" without one of the provided technologies to simply publish a static page (using html/css/js).
Of course, this would also be possible with PHP etc., but you could avoid a lot of overhead, I guess.

**Comment by tiff** [comment]
:+1:

**Comment by tiff** [comment]
This is basically what we would need for it: https://github.com/pearkes/heroku-buildpack-static

**Comment by kdomanski** [comment]
Implemented in development channel.
Example: https://github.com/experimental-platform/nginx-hello-world
