### ISSUE TITLE
Some App 'open'-links under My Apps have a wrong target.

### ISSUE THREAD

**Issue by eddiesel** [experimental-platform/platform-configure-script#12]
![my_apps_app_open_link](https://cloud.githubusercontent.com/assets/644588/9105601/7da5bf68-3c19-11e5-8c1c-c7ef4cc691b1.png)

**Comment by bastianallgeier** [comment]
+1

**Comment by tiff** [comment]
this should be fixed with experimental-platform/platform-configure/pull/13 - I'm testing it over the next days

**Comment by tiff** [comment]
fixed
