### ISSUE TITLE
The message 'Waiting for your app to be deployed...' does not disappear after a deployment.

### ISSUE THREAD

**Issue by eddiesel** [experimental-platform/platform-configure-script#17]
![waiting_for_deployment](https://cloud.githubusercontent.com/assets/644588/9107174/9921bfba-3c25-11e5-9654-aca0c7b97629.png)

**Comment by eddiesel** [comment]
Sorry, it's a duplicate of #9 !

**Comment by tiff** [comment]
:+1:
