### ISSUE TITLE
Unable to access USB devices within app

### ISSUE THREAD

**Issue by tiff** [experimental-platform/platform-configure-script#20]
`lsusb` is not installed. Installing and running it shows an error.

Also directory `/dev/bus/usb` doesn't exist.
Would be nice to access it in order to work with hardware connected over usb.

**Comment by maksdampf** [comment]
Just in case somebody wants to go a little further with USB implementation and wants to use webcam streaming in an app:

Almost all modern webcams are so called "USB Video Class" devices. The kernel driver for UVC devices is `uvcvideo`

pre UVC usb webcams can mostly be used with the  "generic software package for camera adapters" = `gspca` driver library.

both can be found here: http://git.linuxtv.org/

making a stream of the webcam video can be achieved using `MJPEG-streamer`:
https://wiki.ubuntuusers.de/MJPG-Streamer

inputting this

```
export LD_LIBRARY_PATH=/usr/local/lib
mjpg_streamer -i "input_uvc.so -d /dev/video0" -o "output_http.so -p 8080 -w /usr/local/www" 
```

will result in a stream available on `http://localhost:8080`and this command line output:

```
 MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 5
 i: Format............: MJPEG
 o: www-folder-path...: /usr/local/www/
 o: HTTP TCP port.....: 8080
 o: username:password.: disabled
 o: commands..........: enabled
```

for simple recording to disk `ffmpeg` can be used:

```
$ ffmpeg -f v4l2 -s 640x480 -i /dev/video0 output.mpg
```

**Comment by tiff** [comment]
Test case for `lsusb` https://github.com/experimental-platform/test-integration-nodejs/pull/4

**Comment by tiff** [comment]
@hinnerk this isn't fixed yet, we still need to load the required drivers.

**Comment by tiff** [comment]
`lsusb` now works within the app but the apps don't have permissions to access the serial ports. Already working on that.

**Comment by tiff** [comment]
this is fixed with recent releases
