### ISSUE TITLE
Pushing Node.js sample fails with [8] System error: no such file or directory

### ISSUE THREAD

**Issue by mschm** [experimental-platform/platform-configure-script#29]
Attempts to push Node.js apps keep failing. 
System is clean with up to date Alpha.

```
Pushing to ssh://dokku@skylabs.local:8022/node-js-sample
remote: [1G-----> Cleaning up...        
remote: [1G-----> Building node-js-sample from buildstep...        
remote: time="2015-08-18T16:19:33Z" level=fatal msg="Error response from daemon: Cannot start container be23ab2352728ae5b141874b6ade8e8ebb15412c59bbc74ee519f37379ceb948: [8] System error: no such file or directory"         
To ssh://dokku@skylabs.local:8022/node-js-sample
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://dokku@skylabs.local:8022/node-js-sample'
```

**Comment by tiff** [comment]
@mschm Please try again with recent release and provide feedback. Thanks! If it then still doesn't work I would suggest that you invite us for beer to your office and we bring our debugging equipment :smirk:

**Comment by mschm** [comment]
Beer for debugging – deal!!
But I am afraid not with this one... it's fixed :)
Thx!!

**Comment by tiff** [comment]
Seeing this issue again on some of our own machines. Seems not to be fixed. @hinnerk

**Comment by tiff** [comment]
This is the `docker ps` output of a machine that consistently has this problem.
![bildschirmfoto 2015-09-01 um 12 00 36](https://cloud.githubusercontent.com/assets/37363/9601363/43258412-50a1-11e5-9e40-bb0d08d7ce30.png)

**Comment by hinnerk** [comment]
This should be fixed with todays release. Please re-open the ticket if it isn't.
