### ISSUE TITLE
Network very slow

### ISSUE THREAD

**Issue by mgrsskls** [experimental-platform/platform-configure-script#35]
I have the feeling that my internet connection is extremely slow since using the box and that it gets slower and slower the longer I use my network (during the course of the evening after coming home from work e.g.).
I can't really explain or prove it with numbers since I don't know how to measure it. But i just switched off the box and now it's way faster.

And I know, hosting websites of course needs bandwidth, but in the last time there was no app running (not 100% sure - but if there was an app running, it definitely created almost zero traffic).

Could be that I'm wrong and that it doesn't have anything to do with it... But maybe someone has the same experience. :)

**Comment by tiff** [comment]
Interesting: I don't have a logical explanation for that. Maybe you should do a bandwidth test with platform on and off. That would be helpful.

**Comment by mgrsskls** [comment]
Seems like it is caused by something else and the moment when it started was just coincidence :)

**Comment by tiff** [comment]
Phew.
