### ISSUE TITLE
Update fails with syntax error

### ISSUE THREAD

**Issue by dbanck** [experimental-platform/platform-configure-script#40]
I just booted my box after two weeks holidays and started an update.

```
$ sudo /opt/bin/platform-configure
Using channel 'alpha' from /etc/protonet/system/channel.
alpha: Pulling from experimentalplatform/configure
6e6a100fa147: Pull complete
[...]
c7731e2195a5: Pull complete
65e2b38063ce: Pull complete
3fe3458402e9: Already exists
Digest: sha256:671aa6896df3d7f27800a9bfd844768eb13578ce5b739f610f3c3b66b4841d2f
Status: Downloaded newer image for experimentalplatform/configure:alpha
/opt/bin/platform-configure: line 122: syntax error near unexpected token `)'
```

Starting the update process again will work somehow

**Comment by kdomanski** [comment]
@hinnerk IMO the lack of version tag [here](../blob/c1d70c2a196d8c9d6b7d34007ef7bdd8c6177f32/platform-configure.sh#L121) plus [this](../blob/c1d70c2a196d8c9d6b7d34007ef7bdd8c6177f32/platform-configure.sh#L53) is the cause. #43 should fix it.

**Comment by hinnerk** [comment]
@kdomanski second half of the fix: experimental-platform/platform-configure-script#45
