### ISSUE TITLE
Bonjour paleale.local doesn't seem to work

### ISSUE THREAD

**Issue by tiff** [experimental-platform/platform-configure-script#5]
On some linux, windows and osx computers the bonjour address can't be resolved.

**Comment by mgrsskls** [comment]
Same here. I don't know if it's related, but the created git remote url (`ssh://dokku@foo.local:8022/bar`) also doesn't work. I have to use the IP instead of `foo.local`.

**Comment by tiff** [comment]
@mgrossklaus does http://your-box-name/ (without .local) work for you?
Do you have a custom DNS (eg google dns 8.8.8.8) configured at your mac?

**Comment by mgrsskls** [comment]
Nope, that doesn't work as well, and nope, no custom DNS configured.

What just came into my mind is that it didn't work for my protonet box as well. I also had to add an entry in my hosts file for it. So maybe it's a problem with my OS (Mavericks btw).

**Comment by tiff** [comment]
Thanks, @mgrossklaus! We are unable to reproduce the issue. Which router are you using in your network? Can you install the Bonjour Browser from http://www.tildesoft.com/ and send us a screenshot of it? Thank you :)

**Comment by mgrsskls** [comment]
Alice Modem WLAN 1421 (Astoria Networks)

![bildschirmfoto-2015-08-10-um-20 23 58](https://cloud.githubusercontent.com/assets/1113765/9179769/fac148d6-3f9e-11e5-8a17-c90354e7586f.png)

Edit: haha, don't know why I made that local IP addresses blurry... Ignore that :P Or do you need them?

**Comment by tiff** [comment]
Wow, thanks. Can you reach http://mgrsskls-2.local from within your local network?

**Comment by mgrsskls** [comment]
Not 100% but quite sure that I can't.
mgrsskls-2 is my protonet box btw (but I guess you are aware of that :)). When I turn it off that list is almost empty. (Can't test it right now)
I also tried to fix that whole bonjour issue on my own yesterday but couldn't find anything. I know that there are some issues when using Yosemite... but as already mentioned I'm using Mavericks.

**Comment by hinnerk** [comment]
@mgrossklaus This is quite hard to reproduce. Could you please try the command `host -t soa local` in the terminal of your local machine? It should return something like `Host local not found: 3(NXDOMAIN)`.

**Comment by mgrsskls** [comment]
Yip, it returns `Host local not found: 3(NXDOMAIN)`.

**Comment by tiff** [comment]
Same for me, @hinnerk but bonjour works

**Comment by mgrsskls** [comment]
Btw: There's a setting in Safari which shows "bonjour websites" in the bookmarks if activated. This worked for me partially... If I remember correctly my protonet box had been listed there but when I clicked on it it didn't load. Don't know if this is interesting for you but I'll try to verify this tonight.

**Comment by mgrsskls** [comment]
@tiff just verified it: http://mgrsskls-2.local/ doesn't work.

**Comment by tiff** [comment]
@mgrossklaus we're closing this for now. We think that this might be an issue in partiular networks. Please feel free to reopen this when you have an idea or think that this an issue with the platform code :)
