### ISSUE TITLE
System Update Screen not refreshed

### ISSUE THREAD

**Issue by uho** [experimental-platform/platform-configure-script#54]
### System Update Screen not refreshed

When issuing a system update from the configuration page, then the update screen is displayed. This is
fine. However it continues to be displayed even if the update has already finished.
Reloading the configuration page `admin/#/configuration` shows the update success.

**The system should display the configuration page by itself, as soon as the update finished**

**Comment by tiff** [comment]
Hi @uho we fixed this. Try again with the upcoming release. Thanks for reporting!
