### ISSUE TITLE
Update process fails

### ISSUE THREAD

**Issue by mgrsskls** [experimental-platform/platform-configure-script#7]
I'm trying to update the software but nothing happens since... minutes. :)

There are many ongoing polling requests, the json response is always something like this:

```
{"images":{"buildstep:alpha":{"local":"f7f121fe9c81","remote":"f7f121fe"},"central-gateway:alpha":{"local":"4366c34d5947","remote":"fc64ede5"},"app-manager:alpha":{"local":"f77cfbf95e5b","remote":"b83382f2"},"configure:alpha":{"local":"4741ffb9be7b","remote":"4741ffb9"},"dokku:alpha":{"local":"3270d989b944","remote":"843e718b"},"frontend:alpha":{"local":"5a275deaf3e7","remote":"ccd66378"},"hostname-avahi:alpha":{"local":"de3e2d6fff4d","remote":"f7fdc672"},"hostname-smb:alpha":{"local":"b9c2450fe612","remote":"44846779"},"monitoring:alpha":{"local":"493724a31f05","remote":"e680aa29"},"ibuildthecloud":{"local":""},"ptw:alpha":{"local":"3d7385bcbae1","remote":"36811abb"},"skvs:alpha":{"local":"d7787b5b3dda","remote":"a8c31f53"},"systemd-proxy:alpha":{"local":"4e336a04cbfe","remote":"7b307d34"}},"channel":"alpha","up_to_date":false}
```

**Comment by mgrsskls** [comment]
Updating by logging in via ssh worked fine.

**Comment by bastianallgeier** [comment]
The "waiting" screen kept loading forever for me too. I gave up after about 10 minutes and refreshed the admin panel and it told me that the platform is now on the latest version. So basically it seemed to work in the background, but the web installer is somehow broken.

**Comment by tiff** [comment]
@hinnerk I was able to reproduce this easily. It seems that the update is never correctly triggered.
@bastianallgeier Updating via terminal should work, see https://github.com/experimental-platform/platform-configure-script/wiki/Getting-Started-with-Experimental-Platform

**Comment by DarkSwoop** [comment]
Same here. Update via ssh works.

**Comment by hinnerk** [comment]
Yep, it's a bug and I know where it hides => WIP.

**Comment by tiff** [comment]
Also the frontend indicates that there's an update available even though I just updated.
![bildschirmfoto 2015-08-18 um 12 18 27](https://cloud.githubusercontent.com/assets/37363/9327736/5b709650-45a3-11e5-8731-366a8eb3b2c9.png)
